---
### This playbook saves the route table of various devices to a file

- name: Show route table on Cisco
  gather_facts: true
  connection: network_cli
  hosts: cisco

  tasks:
    - name: Show route table - Cisco
      ios_command:
        commands: show ip route
      register: output

    - name: Save route table to file
      copy: content="{{ output.stdout[0] }}" dest="./{{ inventory_hostname }}_route_table.txt"

- name: Show route table on Arista
  gather_facts: true
  connection: network_cli
  hosts: arista

  tasks: 
    - name : Show route table - Arista
      eos_command:
        commands: show ip route
      register: output

    - name: Save route table to file
      copy: content="{{ output.stdout[0] }}" dest="./{{ inventory_hostname }}_route_table.txt"

- name: Show route table on Juniper
  gather_facts: true
  connection: netconf
  hosts: juniper

  tasks:
    - name : Show route table - Juniper
      junos_command:
        commands: show route
      register: output

    - name: Save route table to file
      copy: content="{{ output.stdout[0] }}" dest="./{{ inventory_hostname }}_route_table.txt"

...

