---
### This playbook shows the version that the Cisco, Arista, and Juniper devices are running

- name: Show version on Cisco
  gather_facts: true
  connection: network_cli
  hosts: cisco

  tasks:
    - name: Show version - Cisco
      ios_command:
        commands: show version
      register: output

    - name: Show version output
      debug: 
        msg: "{{ output.stdout_lines }}"

- name: Show version on Arista
  gather_facts: true
  connection: network_cli
  hosts: arista

  tasks: 
    - name : Show version - Arista
      eos_command:
        commands: show version
      register: output

    - name: Show version output
      debug:
        msg: "{{ output.stdout_lines }}"

- name: Show version on Juniper
  gather_facts: true
  connection: netconf
  hosts: juniper

  tasks:
    - name : Show version - Juniper
      junos_command:
        commands: show version
      register: output

    - name: Show version output
      debug:
        msg: "{{ output.stdout_lines }}"
...

